
import 'panel_sync_interval.dart';
class PanelSettings { const PanelSettings({this.panelUrl,this.deviceToken,this.subscriptionUrl,this.configHash,this.enabled=false,this.syncInterval=PanelSyncInterval.defaultInterval,this.lastSyncAt,this.lastError});
  final String? panelUrl, deviceToken, subscriptionUrl, configHash, lastError; final bool enabled; final PanelSyncInterval syncInterval; final DateTime? lastSyncAt;
  Duration get syncIntervalDuration => syncInterval.duration;
  bool get isConfigured => enabled && panelUrl!=null && panelUrl!.trim().isNotEmpty && deviceToken!=null && deviceToken!.trim().isNotEmpty;
  PanelSettings copyWith({String? panelUrl,String? deviceToken,String? subscriptionUrl,String? configHash,bool? enabled,PanelSyncInterval? syncInterval,DateTime? lastSyncAt,String? lastError,bool clearDeviceToken=false,bool clearSubscriptionUrl=false,bool clearConfigHash=false,bool clearLastSyncAt=false,bool clearLastError=false}) => PanelSettings(panelUrl:panelUrl??this.panelUrl,deviceToken:clearDeviceToken?null:(deviceToken??this.deviceToken),subscriptionUrl:clearSubscriptionUrl?null:(subscriptionUrl??this.subscriptionUrl),configHash:clearConfigHash?null:(configHash??this.configHash),enabled:enabled??this.enabled,syncInterval:syncInterval??this.syncInterval,lastSyncAt:clearLastSyncAt?null:(lastSyncAt??this.lastSyncAt),lastError:clearLastError?null:(lastError??this.lastError));
  Map<String,dynamic> toJson({bool includeDeviceToken=false}) => {'panelUrl':panelUrl,if(includeDeviceToken&&deviceToken!=null)'deviceToken':deviceToken,'subscriptionUrl':subscriptionUrl,'configHash':configHash,'enabled':enabled,'syncIntervalMinutes':syncInterval.wireValue,if(lastSyncAt!=null)'lastSyncAt':lastSyncAt!.toUtc().toIso8601String(),if(lastError!=null)'lastError':lastError};
  factory PanelSettings.fromJson(Map<String,dynamic> j) { final r=j['lastSyncAt'] as String?; return PanelSettings(panelUrl:j['panelUrl'] as String?,deviceToken:j['deviceToken'] as String?,subscriptionUrl:j['subscriptionUrl'] as String?,configHash:j['configHash'] as String?,enabled:j['enabled'] as bool? ?? false,syncInterval:PanelSyncInterval.fromWire(j['syncIntervalMinutes'] as String?),lastSyncAt:r==null?null:DateTime.tryParse(r),lastError:j['lastError'] as String?); }
}
