import 'dart:convert';

import '../models/vpn_engine.dart';
import 'config_parser.dart';
import 'link_config_builder.dart';

/// Builds SkadiCore client TOML (`skadicore client --config`).
///
/// SkadiCore v0.1.x client SOCKS5 is no-auth internally. The desktop plugin
/// fronts it with an authenticated SOCKS/HTTP proxy on the public ports so
/// the app still meets the mandatory local-auth security model.
class SkadiConfigBuilder {
  /// Backend (Skadi) listen port = public SOCKS + [internalPortOffset].
  static const internalPortOffset = 200;

  static const defaultPublicSocksPort = ConfigParser.defaultSocksPort;

  static int internalSocksPort([int publicSocksPort = defaultPublicSocksPort]) =>
      publicSocksPort + internalPortOffset;

  /// True when content can run on SkadiCore (VLESS over TCP/TLS/REALITY/XHTTP).
  static bool supportsContent(String content) {
    final trimmed = content.trim();
    if (trimmed.isEmpty) {
      return false;
    }
    if (LinkConfigBuilder.isConfigLink(trimmed)) {
      final scheme = trimmed.split('://').first.toLowerCase();
      return scheme == 'vless';
    }
    try {
      final decoded = jsonDecode(trimmed);
      if (decoded is Map<String, dynamic>) {
        return _proxyOutboundFromXray(decoded) != null;
      }
    } catch (_) {
      // Not JSON.
    }
    return false;
  }

  /// Builds client TOML from a share link or Xray JSON config.
  static String build(
    String content, {
    int publicSocksPort = defaultPublicSocksPort,
    int? backendSocksPort,
  }) {
    final trimmed = content.trim();
    if (trimmed.isEmpty) {
      throw ConfigParserException('Empty config for SkadiCore');
    }

    final Map<String, dynamic> outbound;
    if (LinkConfigBuilder.isConfigLink(trimmed)) {
      if (!supportsContent(trimmed)) {
        throw ConfigParserException(
          'SkadiCore currently supports VLESS only. '
          'Use Auto / Xray / sing-box for other protocols.',
        );
      }
      final xrayJson = LinkConfigBuilder.buildFromLink(
        trimmed,
        VpnEngine.xray,
      );
      outbound = _proxyOutboundFromXray(
            jsonDecode(xrayJson) as Map<String, dynamic>,
          ) ??
          (throw ConfigParserException('No VLESS outbound in built config'));
    } else {
      final decoded = jsonDecode(trimmed);
      if (decoded is! Map<String, dynamic>) {
        throw ConfigParserException('SkadiCore config must be a JSON object');
      }
      outbound = _proxyOutboundFromXray(decoded) ??
          (throw ConfigParserException(
            'SkadiCore requires a VLESS outbound (protocol: vless)',
          ));
    }

    final listenPort = backendSocksPort ?? internalSocksPort(publicSocksPort);
    return _tomlFromXrayOutbound(outbound, listenPort: listenPort);
  }

  static Map<String, dynamic>? _proxyOutboundFromXray(
    Map<String, dynamic> config,
  ) {
    final outbounds = config['outbounds'];
    if (outbounds is! List) {
      return null;
    }
    for (final raw in outbounds) {
      if (raw is! Map) {
        continue;
      }
      final map = Map<String, dynamic>.from(raw);
      final protocol = map['protocol']?.toString().toLowerCase();
      if (protocol == 'vless') {
        return map;
      }
    }
    return null;
  }

  static String _tomlFromXrayOutbound(
    Map<String, dynamic> outbound, {
    required int listenPort,
  }) {
    final settings = outbound['settings'];
    if (settings is! Map) {
      throw ConfigParserException('Invalid VLESS settings');
    }
    final vnext = settings['vnext'];
    if (vnext is! List || vnext.isEmpty || vnext.first is! Map) {
      throw ConfigParserException('Invalid VLESS vnext');
    }
    final server = Map<String, dynamic>.from(vnext.first as Map);
    final address = server['address']?.toString() ?? '';
    final port = server['port'] is int
        ? server['port'] as int
        : int.tryParse('${server['port']}') ?? 0;
    final users = server['users'];
    if (address.isEmpty || port <= 0 || users is! List || users.isEmpty) {
      throw ConfigParserException('Incomplete VLESS server settings');
    }
    final user = Map<String, dynamic>.from(users.first as Map);
    final uuid = user['id']?.toString() ?? '';
    if (uuid.isEmpty) {
      throw ConfigParserException('VLESS UUID missing');
    }

    final stream = outbound['streamSettings'] is Map
        ? Map<String, dynamic>.from(outbound['streamSettings'] as Map)
        : <String, dynamic>{};
    final security = stream['security']?.toString().toLowerCase() ?? 'none';
    final network = stream['network']?.toString().toLowerCase() ?? 'tcp';

    final buffer = StringBuffer()
      ..writeln('# Generated by RioNexTunnel for skadicore client')
      ..writeln('# Do not commit; wiped on disconnect.')
      ..writeln()
      ..writeln('[client]')
      ..writeln('listen = "127.0.0.1:$listenPort"')
      ..writeln()
      ..writeln('[remote]')
      ..writeln('server = "${_escapeToml("$address:$port")}"')
      ..writeln('uuid = "${_escapeToml(uuid)}"')
      ..writeln();

    if (security == 'reality') {
      final reality = stream['realitySettings'] is Map
          ? Map<String, dynamic>.from(stream['realitySettings'] as Map)
          : <String, dynamic>{};
      final password = (reality['password'] ?? reality['publicKey'] ?? '')
          .toString();
      final shortId = (reality['shortId'] ?? '').toString();
      final serverName =
          (reality['serverName'] ?? reality['server_name'] ?? address)
              .toString();
      if (password.isEmpty) {
        throw ConfigParserException('REALITY public key (password) missing');
      }
      buffer
        ..writeln('[remote.tls]')
        ..writeln('enabled = false')
        ..writeln()
        ..writeln('[remote.reality]')
        ..writeln('enabled = true')
        ..writeln('password = "${_escapeToml(password)}"')
        ..writeln('short_id = "${_escapeToml(shortId)}"')
        ..writeln('server_name = "${_escapeToml(serverName)}"')
        ..writeln('kex_mode = "classic"')
        ..writeln();
    } else if (security == 'tls') {
      final tls = stream['tlsSettings'] is Map
          ? Map<String, dynamic>.from(stream['tlsSettings'] as Map)
          : <String, dynamic>{};
      final serverName =
          (tls['serverName'] ?? tls['server_name'] ?? address).toString();
      buffer
        ..writeln('[remote.tls]')
        ..writeln('enabled = true')
        ..writeln('server_name = "${_escapeToml(serverName)}"')
        ..writeln()
        ..writeln('[remote.reality]')
        ..writeln('enabled = false')
        ..writeln();
    } else {
      buffer
        ..writeln('[remote.tls]')
        ..writeln('enabled = false')
        ..writeln()
        ..writeln('[remote.reality]')
        ..writeln('enabled = false')
        ..writeln();
    }

    if (network == 'xhttp' || network == 'splithttp') {
      final xhttp = stream['xhttpSettings'] is Map
          ? Map<String, dynamic>.from(stream['xhttpSettings'] as Map)
          : stream['splithttpSettings'] is Map
              ? Map<String, dynamic>.from(stream['splithttpSettings'] as Map)
              : <String, dynamic>{};
      final path = (xhttp['path'] ?? '/').toString();
      final mode = (xhttp['mode'] ?? 'stream-one').toString();
      final host = xhttp['host']?.toString();
      buffer
        ..writeln('[remote.xhttp]')
        ..writeln('enabled = true')
        ..writeln('path = "${_escapeToml(path)}"')
        ..writeln('mode = "${_escapeToml(mode.isEmpty ? 'stream-one' : mode)}"');
      if (host != null && host.isNotEmpty) {
        buffer.writeln('host = "${_escapeToml(host)}"');
      }
      buffer.writeln();
    }

    return buffer.toString();
  }

  static String _escapeToml(String value) {
    return value
        .replaceAll('\\', '\\\\')
        .replaceAll('"', '\\"')
        .replaceAll('\n', '\\n');
  }
}
